// 25 LUXE signature designs — each uses a different layout archetype (all 25),
// its own hand-picked palette and type pairing, and inherits realistic demo
// copy + photography from a curated family so previews look like real weddings.
// LUXE is a visual collection only: available on the current plans, no extra tier.

import type { ThemeArchetype, WeddingTheme } from "@/lib/wedding-themes";

type L = {
  slug: string;
  name: string;
  family: string;
  tradition: string;
  motif: WeddingTheme["motif"];
  archetype: ThemeArchetype;
  couple: [string, string];
  tagline: string;
  sampleTagline: string;
  description: string;
  c: [bg: string, accent: string, light: string, surface: string, ink: string];
  g: [string, string, string];
  f: [display: string, body: string];
};

const LUXE: L[] = [
  { slug: "udaipur-sheesh-mahal", name: "Sheesh Mahal", family: "royal-rajput", tradition: "North Indian · Rajasthani", motif: "mandala", archetype: "gatefold", couple: ["Aditya", "Rajnandini"], tagline: "Mirror-work maroon opening like palace doors", sampleTagline: "A palace wedding on the shores of Lake Pichola", description: "Gatefold doors part to reveal a mirror-work mandala in ruby and 24k gold — made for City Palace and lakeside havelis.", c: ["#4A0712", "#F0C35A", "#FFF3D9", "#FFF9EF", "#22040A"], g: ["#4A0712", "#7B1224", "#2A030A"], f: ["Cinzel", "Cormorant Garamond"] },
  { slug: "jaipur-pink-city", name: "Pink City Durbar", family: "royal-rajput", tradition: "North Indian · Rajasthani", motif: "haveli", archetype: "cinema", couple: ["Vikram", "Aishwarya"], tagline: "Cinematic rose-sandstone with brass titles", sampleTagline: "Our story, told in the glow of Hawa Mahal", description: "A widescreen opening in Jaipur rose and brass, with film-credit titles and letterboxed photography.", c: ["#7A2E3A", "#F2C68A", "#FFF0EA", "#FFF8F4", "#2E0E14"], g: ["#7A2E3A", "#A8475A", "#4A1520"], f: ["Playfair Display", "Lora"] },
  { slug: "kanjeevaram-gold", name: "Kanjeevaram Zari", family: "south-indian-temple", tradition: "Tamil · Telugu · Kannada", motif: "temple", archetype: "ribbon", couple: ["Srinivas", "Lakshmi"], tagline: "Silk-border ribbons in temple red and zari gold", sampleTagline: "Muhurtham at dawn, blessings for a lifetime", description: "Woven zari ribbons frame the names like a Kanjeevaram border, with a gopuram-tier schedule.", c: ["#7D0F17", "#F4C652", "#FFF2D4", "#FFF8E8", "#2B0608"], g: ["#7D0F17", "#A52128", "#4E070C"], f: ["Yeseva One", "Lora"] },
  { slug: "madurai-lamp", name: "Deepam Glow", family: "south-indian-temple", tradition: "Tamil · Telugu · Kannada", motif: "temple", archetype: "lantern", couple: ["Harish", "Kavya"], tagline: "Brass-lamp glow over deep turmeric", sampleTagline: "Lit by a thousand lamps, joined by one vow", description: "A glowing lamp-lit opening in deep turmeric and brass, inspired by Meenakshi temple evenings.", c: ["#3A1A06", "#F7B733", "#FFF4DA", "#FFFAEE", "#1C0C02"], g: ["#3A1A06", "#6B3410", "#1C0C02"], f: ["Cormorant Garamond", "Lora"] },
  { slug: "kolkata-rajbari", name: "Rajbari Heirloom", family: "bengali-alpona", tradition: "Bengali · Assamese", motif: "alpona", archetype: "letterpress", couple: ["Anirban", "Rituparna"], tagline: "Letterpress cream with sindoor red", sampleTagline: "Shubho Bibaho — from our rajbari to your heart", description: "A pressed-paper invitation feel with deep sindoor ink, alpona corners and rajbari courtyards.", c: ["#F3E8D6", "#B3221F", "#2A1410", "#FFFCF6", "#2A1410"], g: ["#F3E8D6", "#EADAC0", "#F3E8D6"], f: ["Playfair Display", "Merriweather"] },
  { slug: "shantiniketan-sona", name: "Shantiniketan Sona", family: "bengali-alpona", tradition: "Bengali · Assamese", motif: "alpona", archetype: "polaroid", couple: ["Sayan", "Madhurima"], tagline: "Terracotta snapshots with gold-leaf edges", sampleTagline: "Poush mela afternoons, forever together", description: "Scattered instant-photo frames on terracotta, with hand-lettered captions and gold leaf.", c: ["#8E3B1E", "#EFCB7C", "#FFF3E4", "#FFF9F1", "#2F1206"], g: ["#8E3B1E", "#B55A30", "#5A2210"], f: ["Fraunces", "Lora"] },
  { slug: "amritsar-golden", name: "Harmandir Gold", family: "punjabi-anand-karaj", tradition: "Sikh · Punjabi", motif: "khanda", archetype: "halo", couple: ["Gurpreet", "Simran"], tagline: "Golden-temple halo on midnight blue", sampleTagline: "Four laavan, one forever", description: "A radiant gold halo over midnight blue, echoing the Golden Temple reflected at night.", c: ["#0E1A3A", "#F2C14E", "#EEF2FB", "#FBFCFF", "#060C1E"], g: ["#0E1A3A", "#1B2C5C", "#060C1E"], f: ["Cinzel", "Inter"] },
  { slug: "phulkari-bloom", name: "Phulkari Festival", family: "punjabi-anand-karaj", tradition: "Sikh · Punjabi", motif: "khanda", archetype: "mosaic", couple: ["Harjot", "Navneet"], tagline: "Mosaic tiles in phulkari fuchsia and marigold", sampleTagline: "Dhol, giddha and a lifetime of bhangra", description: "A bright mosaic of embroidered tiles in fuchsia, marigold and emerald — pure sangeet energy.", c: ["#8A1450", "#FFC63D", "#FFEFF6", "#FFF8FB", "#2E0519"], g: ["#8A1450", "#B51F6A", "#560A30"], f: ["Yeseva One", "Poppins"] },
  { slug: "jodhpur-blue", name: "Blue City Haveli", family: "marwari-haveli", tradition: "Marwari · Rajasthani", motif: "haveli", archetype: "diagonal", couple: ["Yash", "Riddhi"], tagline: "Indigo-washed walls cut with brass diagonals", sampleTagline: "From Mehrangarh's shadow to our own sunrise", description: "A bold diagonal split of Jodhpur indigo and sandstone, with brass-inlay typography.", c: ["#16326B", "#E8B85C", "#EEF3FC", "#FAFCFF", "#081634"], g: ["#16326B", "#2A4F96", "#0A1B40"], f: ["Playfair Display", "Inter"] },
  { slug: "bikaner-jharokha", name: "Jharokha Silk", family: "marwari-haveli", tradition: "Marwari · Rajasthani", motif: "haveli", archetype: "arcade", couple: ["Kunal", "Shreya"], tagline: "Carved jharokha arches in sandalwood and jade", sampleTagline: "Seven pheras beneath carved sandstone", description: "Sandalwood jharokha windows frame the couple, with jade silk accents and block-print borders.", c: ["#2F4A3C", "#E6C589", "#F2F6EF", "#FCFDF9", "#152219"], g: ["#2F4A3C", "#46685A", "#1A2A21"], f: ["Cormorant Garamond", "Poppins"] },
  { slug: "hyderabad-nizam", name: "Nizam's Court", family: "nikah-emerald", tradition: "Muslim · Nikah", motif: "arch", archetype: "vellum", couple: ["Faizan", "Mehreen"], tagline: "Vellum overlay on emerald with pearl calligraphy", sampleTagline: "Qubool hai — under Chowmahalla's chandeliers", description: "A translucent vellum sheet floats over deep emerald, with pearl-toned calligraphy and jaali arches.", c: ["#0B3A2C", "#E4C98C", "#EEF7F2", "#FAFDFB", "#051E16"], g: ["#0B3A2C", "#135A44", "#051E16"], f: ["Cormorant Garamond", "Lora"] },
  { slug: "lucknow-chikan", name: "Awadhi Chikan", family: "nikah-emerald", tradition: "Muslim · Nikah", motif: "arch", archetype: "monogram", couple: ["Arsalan", "Zoya"], tagline: "Ivory chikankari with an antique gold crest", sampleTagline: "Tehzeeb, tradition and a love to cherish", description: "A monogram crest in antique gold over ivory chikankari textures, inspired by Awadhi courts.", c: ["#F5EFE3", "#A8864A", "#1E1A12", "#FFFFFF", "#1E1A12"], g: ["#F5EFE3", "#EAE0CC", "#F5EFE3"], f: ["Cinzel", "Merriweather"] },
  { slug: "walima-pearl", name: "Pearl Walima", family: "walima-rose", tradition: "Muslim · Walima", motif: "arch", archetype: "scroll", couple: ["Rehan", "Hiba"], tagline: "Dusky rose scroll with pearl flourishes", sampleTagline: "Celebrating our Walima with those we love", description: "A flowing script scroll in dusky rose and pearl, soft and romantic for the Walima dinner.", c: ["#6E3448", "#EBC7B4", "#FFF2EF", "#FFF9F7", "#2A0F18"], g: ["#6E3448", "#955068", "#43192A"], f: ["Playfair Display", "Lora"] },
  { slug: "goa-basilica", name: "Basilica Blanc", family: "christian-chapel", tradition: "Christian · Catholic", motif: "cross", archetype: "framed", couple: ["Joel", "Clarissa"], tagline: "Cathedral white with gilded frames", sampleTagline: "Two hearts, one covenant, before God and family", description: "A gilded invitation frame on cathedral white, with stained-glass blush and Old Goa chapel light.", c: ["#FAF6EF", "#B8924C", "#221C14", "#FFFFFF", "#221C14"], g: ["#FAF6EF", "#F0E7D6", "#FAF6EF"], f: ["Cormorant Garamond", "Inter"] },
  { slug: "shillong-cathedral", name: "Cathedral Hymn", family: "christian-chapel", tradition: "Christian · Protestant", motif: "cross", archetype: "timeline", couple: ["Daniel", "Evangeline"], tagline: "Hymn-book navy with candle-gold ribbons", sampleTagline: "Joined in faith among the pine hills", description: "A hymn-book timeline in navy and candle gold — ceremony, reception and toast, in order.", c: ["#16223D", "#DDB86A", "#EEF2F9", "#FAFBFF", "#0A1120"], g: ["#16223D", "#24365E", "#0A1120"], f: ["Playfair Display", "Merriweather"] },
  { slug: "mumbai-atelier", name: "Colaba Atelier", family: "modern-minimal", tradition: "Contemporary · Editorial", motif: "arch", archetype: "editorial", couple: ["Nikhil", "Tanya"], tagline: "Gallery white, charcoal type, one gold rule", sampleTagline: "A city love story, beautifully edited", description: "A fashion-magazine split with oversized serif names, charcoal type and one fine gold rule.", c: ["#F4F1EC", "#B8975A", "#141414", "#FFFFFF", "#141414"], g: ["#F4F1EC", "#E9E3D9", "#F4F1EC"], f: ["Playfair Display", "Inter"] },
  { slug: "delhi-noir", name: "Lutyens Noir", family: "modern-minimal", tradition: "Contemporary · Black-tie", motif: "arch", archetype: "poster", couple: ["Arjun", "Sanya"], tagline: "Black-tie poster in onyx and champagne", sampleTagline: "Black tie. Champagne. Forever.", description: "An oversized black-tie poster — onyx background, champagne capitals and architectural spacing.", c: ["#0D0D0F", "#D7B46A", "#F5F1E8", "#FFFDF8", "#050506"], g: ["#0D0D0F", "#23232A", "#050506"], f: ["Cinzel", "Inter"] },
  { slug: "bengaluru-grid", name: "Garden City Grid", family: "modern-minimal", tradition: "Contemporary · Modern", motif: "arch", archetype: "grid", couple: ["Siddharth", "Nisha"], tagline: "Modular sage grid with brass numerals", sampleTagline: "Designed together, built to last", description: "A crisp modular grid in sage and brass — clean blocks for names, date, venue and RSVP.", c: ["#2E3E34", "#D4B478", "#F0F4EF", "#FBFDFA", "#141C17"], g: ["#2E3E34", "#435A4B", "#18221C"], f: ["Fraunces", "Inter"] },
  { slug: "goa-sunset-ticket", name: "Anjuna Sunset", family: "goa-beach", tradition: "Coastal · Destination", motif: "waves", archetype: "ticket", couple: ["Rahul", "Alisha"], tagline: "Boarding-pass coral with sunset gold", sampleTagline: "Destination: forever. Boarding at sunset.", description: "A destination boarding-pass layout in coral and sunset gold, with tide-line dividers.", c: ["#B4473A", "#FFD08A", "#FFF1EA", "#FFF9F5", "#3A120C"], g: ["#B4473A", "#DB6A4E", "#7A2A22"], f: ["Fraunces", "Poppins"] },
  { slug: "andaman-lagoon", name: "Havelock Lagoon", family: "goa-beach", tradition: "Coastal · Island", motif: "waves", archetype: "stamp", couple: ["Varun", "Kiara"], tagline: "Postage-stamp lagoon teal with pearl sand", sampleTagline: "Sealed with a kiss on Radhanagar beach", description: "A collectible postage-stamp design in lagoon teal and pearl sand — your wedding, postmarked.", c: ["#0B5561", "#F3D9A4", "#E8F7F7", "#F8FDFD", "#032A30"], g: ["#0B5561", "#137584", "#053239"], f: ["Playfair Display", "Poppins"] },
  { slug: "kumarakom-houseboat", name: "Kettuvallam Gold", family: "kerala-backwaters", tradition: "Malayali · Coastal South", motif: "palm", archetype: "column", couple: ["Anand", "Parvathy"], tagline: "Kasavu cream with a single gold border", sampleTagline: "Thaali, thulasi and the quiet of the backwaters", description: "A narrow kasavu-inspired column in cream and gold, calm as a houseboat drifting on Vembanad.", c: ["#F6F0DF", "#B99140", "#1F1A0E", "#FFFDF6", "#1F1A0E"], g: ["#F6F0DF", "#ECE2C6", "#F6F0DF"], f: ["Cormorant Garamond", "Lora"] },
  { slug: "munnar-mist", name: "Munnar Mist", family: "kerala-backwaters", tradition: "Malayali · Hill Station", motif: "palm", archetype: "panel", couple: ["Jithin", "Aparna"], tagline: "Tea-garden green with a misty side panel", sampleTagline: "Vows among the tea hills, wrapped in mist", description: "A tea-garden side panel in deep leaf green, with mist-soft photography and brass accents.", c: ["#1F3D2B", "#D8BD7E", "#EFF6F0", "#FAFDFA", "#0E1E15"], g: ["#1F3D2B", "#2F5A40", "#0E1E15"], f: ["Fraunces", "Lora"] },
  { slug: "rishikesh-boho", name: "Ganga Boho", family: "boho-destination", tradition: "Boho · Global · Destination", motif: "boho", archetype: "collage", couple: ["Dev", "Myra"], tagline: "Sun-bleached linen collage with pampas gold", sampleTagline: "Barefoot by the Ganga, hearts wide open", description: "A layered linen-and-pampas photo collage in sand and dried-rose tones — for riverside boho weddings.", c: ["#8C6A55", "#F2D7A8", "#FFF5EC", "#FFFAF5", "#2E2016"], g: ["#8C6A55", "#A98670", "#5E4535"], f: ["Cormorant Garamond", "Poppins"] },
  { slug: "tuscany-long-table", name: "Long Table Soirée", family: "boho-destination", tradition: "Boho · International", motif: "boho", archetype: "marquee", couple: ["Kabir", "Leah"], tagline: "Olive-grove marquee lights over terracotta", sampleTagline: "Good wine, long tables, forever friends", description: "A festoon-light marquee banner over olive and terracotta — made for vineyard and villa weddings.", c: ["#5A5A32", "#F0C987", "#F6F4E8", "#FDFCF6", "#23230F"], g: ["#5A5A32", "#77774A", "#35351C"], f: ["Playfair Display", "Lora"] },
  { slug: "kashi-classic", name: "Kashi Sandhya", family: "royal-rajput", tradition: "Hindu · Vedic", motif: "mandala", archetype: "classic", couple: ["Pranav", "Gauri"], tagline: "Saffron dusk over the ghats, gold mandala", sampleTagline: "Saat phere, saat vachan, ek jeevan", description: "A timeless centred design in saffron dusk and gold, inspired by Ganga aarti on the Varanasi ghats.", c: ["#8A3410", "#F6C860", "#FFF3DE", "#FFF9EF", "#2E1004"], g: ["#8A3410", "#B34E1C", "#561E06"], f: ["Cormorant Garamond", "Lora"] },
];

export const LUXE_THEMES: WeddingTheme[] = LUXE.map((x) => ({
  id: `luxe25-${x.slug}`,
  name: x.name,
  tradition: x.tradition,
  tagline: x.tagline,
  description: x.description,
  colors: { bg: x.c[0], accent: x.c[1], light: x.c[2], surface: x.c[3], ink: x.c[4] },
  fonts: { display: x.f[0], body: x.f[1] },
  motif: x.motif,
  archetype: x.archetype,
  heroGradient: `linear-gradient(135deg,${x.g[0]} 0%,${x.g[1]} 55%,${x.g[2]} 100%)`,
  sampleCouple: x.couple,
  sampleTagline: x.sampleTagline,
  tier: "standard",
  family: x.family,
  luxe: true,
}));
